# Tema Shinobu — roxo/magenta neon

background            #0d0a14
foreground            #e9d5ff
cursor                #d946ef
selection_background  #8b5cf6
selection_foreground  #0d0a14

# black
color0   #1a0f2e
color8   #2a1a40

# red
color1   #f472b6
color9   #f472b6

# green
color2   #a78bca
color10  #c4a8e0

# yellow
color3   #d946ef
color11  #e879f9

# blue
color4   #8b5cf6
color12  #a78bfa

# magenta
color5   #c026d3
color13  #e879f9

# cyan
color6   #8b5cf6
color14  #a78bfa

# white
color7   #e9d5ff
color15  #ffffff

background_opacity    0.90
