k# --- Tema Shinobu Kocho ---

# Cores Principais
background #1e1e2e
foreground #cdd6f4
cursor #cba6f7
cursor_text_color #1e1e2e
selection_background #f5c2e7
selection_foreground #1e1e2e

# Transparência do fundo (Ajuste de 0.0 a 1.0)
background_opacity 0.7

# Paleta de Cores do Terminal
# Preto/Cinza Escuro
color0 #45475a
color8 #585b70
# Vermelho/Rosa Escuro
color1 #f38ba8
color9 #f38ba8
# Verde
color2  #a6e3a1
color10 #a6e3a1
# Amarelo
color3  #f9e2af
color11 #f9e2af
# Azul Claro (Borboleta)
color4  #89b4fa
color12 #89b4fa
# Roxo/Magenta (Shinobu)
color5  #cba6f7
color13 #cba6f7
# Ciano
color6  #94e2d5
color14 #94e2d5
# Branco/Cinza Claro
color7  #bac2de
color15 #a6adc8
