monitor=,preferred,auto,1
exec-once=kitty
exec-once=waybar
exec-once = setsid swww-daemon --format xrgb
input {
    kb_layout = br
    kb_variant = abnt2
}

bind = SUPER, Q, killactive,
bind = SUPER, RETURN, exec, kitty
bind = SUPER, B, exec, firefox
bind = SUPER, C, exec, code
bind = SUPER, D, exec, wofi --show drun --style ~/.config/wofi/style.css

# Gravar área selecionada (Super + Shift + R)
bind = SUPER SHIFT, R, exec, wf-recorder -g "$(slurp)" -f ~/Videos/$(date +'%Y-%m-%d_%H%M%S.mp4')

# Parar a gravação (Super + Shift + S)
bind = SUPER SHIFT, S, exec, pkill wf-recorder

# WorkSpace
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

# Mover janela ativa para o workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

# Abre o btop flutuante, centralizado e com um tamanho fixo
bind = SUPER SHIFT, G, exec, kitty --title btop-float -e btop

# Abrir Thunar com SUPER + E
bind = SUPER, E, exec, thunar

# Arrastar janelas com SUPER + Clique Esquerdo
bindm = SUPER, mouse:272, movewindow

# Redimensionar janelas com SUPER + Clique Direito
bindm = SUPER, mouse:273, resizewindow

# Copiar área selecionada para a área de transferência (Ctrl+V)
bind = SHIFT, Print, exec, grim -g "$(slurp)" - | wl-copy

# Copiar a tela inteira para a área de transferência
bind = , Print, exec, grim - | wl-copy

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 6
        passes = 2
        ignore_opacity = true
    }
}

general {
    # Espaçamento entre as janelas (para o papel de parede aparecer mais)
    gaps_in = 5
    gaps_out = 10
    
    # Grossura da borda (coloquei 2 para o degradê ficar bem visível)
    border_size = 2
    
    # Borda ativa: Degradê Roxo para Rosa em 45 graus (Shinobu)
    col.active_border = rgba(cba6f7ff) rgba(f5c2e7ff) 45deg
    
    # Borda inativa: Um roxo/cinza super escuro e quase transparente
    col.inactive_border = rgba(313244aa)
}

bind = SUPER, W, exec, ~/scripts/trocar_wallpaper.sh

